In [5]:
import numpy as np

In [18]:
my_list=np.array([1,2,3,4,5,6],dtype=float)

In [19]:
print(my_list)

[1. 2. 3. 4. 5. 6.]


In [20]:
type(my_list)

numpy.ndarray

In [21]:
len(my_list)

6

In [22]:
my_list.ndim

1

In [23]:
my_list.shape

(6,)

In [37]:
array=my_list.reshape(2,-1)

In [38]:
array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
array.ndim

2

In [40]:
array.shape

(2, 3)

In [41]:
list1=[1,2,3,4]
list2=[2,3,4,5]
list3=[3,4,5,6]

In [43]:
array_1=np.array([list1,list2,list3])

In [44]:
array_1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [45]:
array_2=array_1.reshape(2,-1)

In [46]:
array_2

array([[1, 2, 3, 4, 2, 3],
       [4, 5, 3, 4, 5, 6]])

In [47]:
array_2.shape

(2, 6)

In [48]:
r=range(1,4)

In [50]:
print(r)

range(1, 4)


In [59]:
arr=np.arange(0,24,3)

In [60]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [62]:
arr.reshape(4,-1)

array([[ 0,  3],
       [ 6,  9],
       [12, 15],
       [18, 21]])

In [65]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])

In [66]:
arr1+arr2

array([[2, 4],
       [6, 8]])

In [67]:
np.add(arr1,arr2)

array([[2, 4],
       [6, 8]])

In [68]:
arr1-arr2

array([[0, 0],
       [0, 0]])

In [69]:
np.subtract(arr1,arr2)

array([[0, 0],
       [0, 0]])

In [70]:
arr1*arr2

array([[ 1,  4],
       [ 9, 16]])

In [74]:
np.dot(arr1,arr2)
arr1.dot(arr2)

array([[ 7, 10],
       [15, 22]])

In [73]:
np.divide(arr1,arr2)

array([[1., 1.],
       [1., 1.]])

In [78]:
print(np.sum(array_1))

42


In [79]:
print(np.sum(array_1,axis=0))

[ 6  9 12 15]


In [80]:
print(np.sum(array_1,axis=1))

[10 14 18]
